import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/custom/Navbar/NavBar";
import Footer from "@/components/custom/Footer/Footer";
import Sidebar from "@/components/custom/Sidebar";
import { ToastContainer } from 'react-toastify';
import Kernel from "@/config/Kernel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body>
        <Kernel>
          <NavBar />
          <ToastContainer position="top-center" autoClose={3000} />
          <Sidebar />
          {children}
          <Footer />
        </Kernel>
      </body>
    </html>
  );
}
